# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: makeall
        name: Make All
        entry: make
        language: system
        always_run: true
        types: [python]
        stages:
            - push
            - manual
