# Generated by Django 4.0.3 on 2022-03-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_create_task_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('id',), 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
